### PR TITLE
[doc]: README--Updated contribution guidelines

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Readme updates:
- added TOC
- updated installation and build instructions
- added Git-related info
- added release procedure

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/82)

### CODE REVIEW

**Review by JameStark — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/82#-:-NF9ShGL9lyaoOXkxoKE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @glrn)

**Review by LucasLvy — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/82)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ArielElp, @bbrandtom, and @glrn)

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-82/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-82/documentation/ .

**Pull request merged**
