### PR TITLE
chore: Converting Hello StarkNet from RST to AsciiDoc

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Converting Hello StarkNet from RST to AsciiDoc.

### Preview

https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/hello_starknet/

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)

### CODE REVIEW

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @stoobie)

___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 7 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGBKGH0619J8yAySQHw:-NGBKGH0619J8yAySQHx:bst60df) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/39130e31a729b5de8d4fc5a52cd026dd3f5fe5f0/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L7)):*
> ```AsciiDoc
> == Installation
> 
> Follow the installation instructions for the `cairo-lang` package in link:https://starknet.io/docs/quickstart.html[Setting up the environment^].
> ```

Please use lines of length <= 100 chars.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @stoobie)

___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 26 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGBKfCA7nlzYbz8F5Uh:-NGBKfCA7nlzYbz8F5Ui:bq7uuag) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/39130e31a729b5de8d4fc5a52cd026dd3f5fe5f0/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L26)):*
> ```AsciiDoc
> To interact with StarkNet, you will need to deploy an account contract. In this tutorial, we will use a slightly modified version of OpenZeppelin’s standard for EOA contract (at the moment, the signature is computed differently). Set the `STARKNET_WALLET` environment variable as follows:
> 
> [source,bash]
> ```

Missing id. Make sure all `tested-code` sections have exactly the same id they had in the original files.

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @liorgold2 and @stoobie)

___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 7 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGBKGH0619J8yAySQHw:-NGC0yE4B-QCOmKbP-6I:bhy9ot6) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/39130e31a729b5de8d4fc5a52cd026dd3f5fe5f0/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L7)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Please use lines of length <= 100 chars.
</blockquote></details>

Will do.
___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 26 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGBKfCA7nlzYbz8F5Uh:-NGBut1K3fa0E3M7nwk_:bhy9ot6) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/39130e31a729b5de8d4fc5a52cd026dd3f5fe5f0/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L26)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

Missing id. Make sure all `tested-code` sections have exactly the same id they had in the original files. 
</blockquote></details>

Will do.

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @liorgold2)

___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 7 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGBKGH0619J8yAySQHw:-NGCc4WzDRXxItWm8t_0:b-w9ef0v) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/39130e31a729b5de8d4fc5a52cd026dd3f5fe5f0/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L7)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done. There were some specific places that I couldn't shorten, either links/xrefs or code examples.
___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 26 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGBKfCA7nlzYbz8F5Uh:-NGCc3311GisEbHfvFim:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/39130e31a729b5de8d4fc5a52cd026dd3f5fe5f0/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L26)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.

**Review by liorgold2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @stoobie)

___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 148 at r9](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGCo3Yd8AhN64dlDNRG:-NGCo3Ye2KaTgT3t4Gnj:b-d5ww7m) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/75f44e506ba483979730a9752fcd6da10329cee7/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L148)):*
> ```AsciiDoc
> are not deployed using the proxy pattern, so they cannot be upgraded and may stop working in future
> versions of StarkNet.
> ====
> ```

End files with the new-line character.

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @liorgold2)

___
*[`components/StarkNet/modules/hello_starknet/pages/account_setup.adoc` line 148 at r9](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/100#-NGCo3Yd8AhN64dlDNRG:-NGD31bQ5V45pEXDQTrk:bb6un1j) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/75f44e506ba483979730a9752fcd6da10329cee7/components/StarkNet/modules/hello_starknet/pages/account_setup.adoc#L148)):*
<details><summary><i>Previously, liorgold2 wrote…</i></summary><blockquote>

End files with the new-line character.
</blockquote></details>

Done

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-100/documentation/ .

**Comment by stoobie** [comment]
@stoobie @JameStark I need to fix some style sheet issues. Notice that in the preview the header colors and font sizes have changed.

The style sheet from the UI bundle is slightly out of sync with the site_default.css in the supplemental files.

**Comment by stoobie** [comment]
I moved the files that provide support for Cairo syntax highlighting to a separate PR, because there's some CSS clean up to do, and I don't want that to hold up this PR.

**Pull request merged**
