### PR TITLE
fix: Fixed a few typos and Contract Hash -> Class Hash

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Fixed a few typos and misphrasing.

#### Preview URLs

https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/develop/Contracts/contract-hash/
https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/develop/Hashing/hash-functions/
https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/develop/State/starknet-state/

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)

### CODE REVIEW

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 5 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFbkCgTDJrFOMW1v4ZA:-NFbkCgTDJrFOMW1v4ZB:b5qgz48) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d9903863fcdb920d9524812c4cd91db2e21481b1/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L5)):*
> ```AsciiDoc
> :stem: latexmath
> 
> The contract's hash is actually a hash of the parent class of the contract.
> ```

We are describing the class hash, not the contract hash



_Suggestion:_
```AsciiDoc
The class hash is a hash chain of it's definition.
```
___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 7 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFbkNlb1PX3NaDKrkNS:-NFbkNlb1PX3NaDKrkNT:b-7s6zcd) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d9903863fcdb920d9524812c4cd91db2e21481b1/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L7)):*
> ```AsciiDoc
> The contract's hash is actually a hash of the parent class of the contract.
> 
> == Elements that define a contract
> ```

class



_Code quote:_
```AsciiDoc
 contract
```
___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 9 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFbkOdD67FEEjYuNxhV:-NFbkOdD67FEEjYuNxhW:bb9liwa) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d9903863fcdb920d9524812c4cd91db2e21481b1/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L9)):*
> ```AsciiDoc
> == Elements that define a contract
> 
> The elements that define a contract are:
> ```

Same for the whole page.
Please make sure you understand the distinction between the two with Ariel.



_Suggestion:_
```AsciiDoc
class
```

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 5 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFbkCgTDJrFOMW1v4ZA:-NFguy0A8nNFNEnYoqe_:b8jp211) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d9903863fcdb920d9524812c4cd91db2e21481b1/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L5)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

We are describing the class hash, not the contract hash
</blockquote></details>

Fixed. I changed this to:
`The class hash is a hash chain of the definition of the class.`

The section immediately following is entitled: `Definition of a class` and following that is `How the class hash is computed`.
___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 7 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFbkNlb1PX3NaDKrkNS:-NFh-1-84JPnEfLZskBc:bt2vr1b) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d9903863fcdb920d9524812c4cd91db2e21481b1/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L7)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

class
</blockquote></details>

Fixed.
___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 9 at r4](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFbkOdD67FEEjYuNxhV:-NFgz_4Z4aQb-Yut5h33:b-6spqsl) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d9903863fcdb920d9524812c4cd91db2e21481b1/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L9)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

Same for the whole page.
Please make sure you understand the distinction between the two with Ariel.
</blockquote></details>

Done, except for names of files we link to:
https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/starknet/core/os/contracts.cairo
https://github.com/starkware-libs/cairo-lang/blob/7712b21fc3b1cb02321a58d0c0579f5370147a8b/src/starkware/starknet/core/os/contract_hash.py

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 11 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFiOiKC4BYBZD2BvYmu:-NFiOiKC4BYBZD2BvYmv:b-3j6mxm) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/6eac90532f79c6aed8a769f7ae6c29e554604870/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L11)):*
> ```AsciiDoc
> The elements that define a class are:
> 
> API version:: The version of the API under which the class was deployed.
> ```

change to: "The version of the class, currently always 0".



_Code quote:_
```AsciiDoc
The version of the API under which the class was deployed
```
___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 22 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFiE3VP78pMDzkds0wy:-NFiE3VP78pMDzkds0wz:b-amcmzc) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/6eac90532f79c6aed8a769f7ae6c29e554604870/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L22)):*
> ```AsciiDoc
> Array of constructors entry points:: Currently, the compiler allows only one constructor.
> Array of used builtin names:: An ASCII-encode array, ordered by declaration.
> Keccak:: The xref:../Hashing/hash-functions.adoc#starknet-keccak[starknet_keccak], of the class's program. The class's program is the `.json` file that the StarkNet compiler outputs when you run the following command:
> ```

Replace the title with "Program hash"



_Code quote:_
```AsciiDoc
Keccak
```

**Review by bbrandtom — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-:-NFrBWr5Cd2yXaWNyNdL:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @stoobie)

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 11 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFiOiKC4BYBZD2BvYmu:-NFsEX3c1EwOJzuXLpxp:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/6eac90532f79c6aed8a769f7ae6c29e554604870/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L11)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

change to: "The version of the class, currently always 0".
</blockquote></details>

Done.
___
*[`components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc` line 22 at r5](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-NFiE3VP78pMDzkds0wy:-NFsEpYODqSpvNgDZdKr:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/6eac90532f79c6aed8a769f7ae6c29e554604870/components/StarkNet/modules/develop/pages/Contracts/contract-hash.adoc#L22)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Replace the title with "Program hash"
</blockquote></details>

Done.

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Review by bbrandtom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-:-NFsmZyj1JXIfjkylG6S:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @bbrandtom)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89#-:-NFsrPw-EuzyrjT5cDqP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-89/documentation/ .

**Review by stoobie — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r4, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)* status: all files reviewed, 1 unresolved discussion (waiting on @bbrandtom)

**Review by stoobie — COMMENTED** [review]
> Dismissed @bbrandtom from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bbrandtom)

**Pull request merged**
