### PR TITLE
chore: Added a section for the PR preview to the PR template.

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/96)

### CODE REVIEW

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-96/documentation/ .

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-96/documentation/ .

**Review by JameStark — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/96#-:-NGG2d2T4WNAPdFrxdzp:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-96/documentation/ .

**Review by stoobie — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/96)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Pull request merged**
