### PR TITLE
docs: nonce in on chain data and the state definition

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)

### CODE REVIEW

**Review by stoobie — CHANGES_REQUESTED** [review]
@ArielElp Please change the name of the directory from Data Availability to Data_Availability.

I'll add more comments soon.

**Review by stoobie — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`docs/Data Availabilty/on-chain-data.md` line 22 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF2Y3d-pHKPKS_3tfP:-NAF2Y3d-pHKPKS_3tfQ:bx5a15v) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/Data%20Availabilty/on-chain-data.md#L22)):*
> ```Markdown
> - For each such contract, we have:
>   - `contract_address` - the [address](../Contracts/contract-address.md) of the contract
>   - `num_of_storage_updates | nonce ` - a uint256 that encodes both the number of storage updates for that contract and the updated nonce:
> ```

uint256 is an adjective. What is the noun that should follow? *field*? *value*? Also, the way it's notated, it appears that this is one possible field whose syntax is:

num_of_storage_updates | nonce. I think you mean it to be `num_of_storage_updates` or `nonce`. If so, then it should be written like this:
`num_of_storage_updates` | `nonce `



_Code quote:_
```Markdown
uint256
```
___
*[`docs/Data Availabilty/on-chain-data.md` line 98 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF3stF7KMJXReCb8IT:-NAF3stF7KMJXReCb8IU:b32wof) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/Data%20Availabilty/on-chain-data.md#L98)):*
> ```Markdown
>   - Following the above contract address, we have `18446744073709551617` (index 8 in the array), which is $2^{64}+1$, thus:
>     - The new contact nonce is 1
>     - One storage key was updated
> ```

is



_Code quote:_
```Markdown
was
```
___
*[`docs/Data Availabilty/on-chain-data.md` line 99 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF3GvmBHzUGF7AZUY7:-NAF3GvmBHzUGF7AZUY8:b-h8lgyp) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/5fb03f4c74802c6978f17fbdfa7efcc5eb3596ca/docs/Data%20Availabilty/on-chain-data.md#L99)):*
> ```Markdown
> ## Extract from Ethereum
> 
> The data described above is sent across several Ethereum transactions, each holding a part of this array as calldata. Each new StarkNet block has its associated state diff transactions. You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation. You may also take a look at the [python script](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/resources/fact_retrieval.py) which extracts the same information.
> ```

You can find the code for extracting this data from Ethereum in the repo for Pathfinder, the first StarkNet full node implementation. See [Pathfinder's repo].(https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs).



_Code quote:_
```Markdown
You may find the code for extracting this data from Ethereum in [Pathfinder's repo](https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs). Pathfinder is the first StarkNet full node implementation.
```
___
*[`docs/State/starknet-state.md` line 14 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF1Jt0Ar0K5je7Mk2H:-NAF1Jt0Ar0K5je7Mk2I:b-mhf9i2) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L14)):*
> ```Markdown
> - contract nonce - the number of transactions sent from this contract
> 
> :::info nonce
> ```

This should not be "Info" This should be its own section. This is of high importance, and a Note/Info is something that is interesting but can be safely ignored.



_Code quote:_
```Markdown
:::info nonce
```
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF0pd00KcxTg6IiFbe:-NAF0pd00KcxTg6IiFbf:bqten13) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
> ```Markdown
> 
> :::info nonce
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> ```

contract



_Code quote:_
```Markdown
contact 
```
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF0yiNE_Mk8Y0YVbzz:-NAF0yiO-ZnULsZIrFJi:bard2w5) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
> ```Markdown
> 
> :::info nonce
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> ```

that protects against replays



_Code quote:_
```Markdown
which is used to provide replay protection
```
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF14HGDz7OiByifGyW:-NAF14HGDz7OiByifGyX:bb7ky32) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
> ```Markdown
> 
> :::info nonce
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> ```

must



_Code quote:_
```Markdown
has to 
```
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF17Z0338tQ132c7hy:-NAF17Z0338tQ132c7hz:b32woa) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
> ```Markdown
> 
> :::info nonce
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> ```

in



_Code quote:_
```Markdown
on
```
___
*[`docs/State/starknet-state.md` line 17 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF1h2YAaCZD2iTMpku:-NAF1h2YAaCZD2iTMpkv:buomyxp) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L17)):*
> ```Markdown
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> 
> Note that while in Ethereum, only EOAs may send transactios and consequently have a non-zero nonce, in StarkNet, only account contracts may send transactions and have a non-zero nonce.
> ```

I try to avoid "Note that". Usually I either pull the info in it's own Note, or if it doesn't require a note, I change it to "Be aware that" to avoid too much use of the word "Note".



_Code quote:_
```Markdown
Note that
```
___
*[`docs/State/starknet-state.md` line 17 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF1wsZ7LFPR5LpIwHv:-NAF1wsZ7LFPR5LpIwHw:bnquz52) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L17)):*
> ```Markdown
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> 
> Note that while in Ethereum, only EOAs may send transactios and consequently have a non-zero nonce, in StarkNet, only account contracts may send transactions and have a non-zero nonce.
> ```

General rule: Do NOT use the word "may". It's ambiguous. Use either "might" or "can". In this case, you mean "can".



_Code quote:_
```Markdown
may
```
___
*[`docs/State/starknet-state.md` line 17 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF2BvN9NLwFRTOQnZE:-NAF2BvN9NLwFRTOQnZF:b-kn9zla) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L17)):*
> ```Markdown
> Similarly to Ethereum, the nonce is an attribute of a contact which is used to provide replay protection at the protocol level. When a transaction is sent from a given contract, the nonce field on the transaction has to match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.
> 
> Note that while in Ethereum, only EOAs may send transactios and consequently have a non-zero nonce, in StarkNet, only account contracts may send transactions and have a non-zero nonce.
> ```

transactions,



_Code quote:_
```Markdown
transactios
```

**Review by bbrandtom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-:-NAJMGI39arV6cP-Z26i:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp)

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Data Availabilty/on-chain-data.md` line 22 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF2Y3d-pHKPKS_3tfP:-NAIaSI7-AyNuDzEcDuV:bvrneq5) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/Data%20Availabilty/on-chain-data.md#L22)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

uint256 is an adjective. What is the noun that should follow? *field*? *value*? Also, the way it's notated, it appears that this is one possible field whose syntax is:

num_of_storage_updates | nonce. I think you mean it to be `num_of_storage_updates` or `nonce`. If so, then it should be written like this:
`num_of_storage_updates` | `nonce `
</blockquote></details>

Added "value"

It's concatenation, not OR.
___
*[`docs/Data Availabilty/on-chain-data.md` line 98 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF3stF7KMJXReCb8IT:-NAIZU9bAzdjeEOOomrx:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/Data%20Availabilty/on-chain-data.md#L98)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

is
</blockquote></details>

Done.
___
*[`docs/Data Availabilty/on-chain-data.md` line 99 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF3GvmBHzUGF7AZUY7:-NAIarRCC4P03fCTIWyi:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/5fb03f4c74802c6978f17fbdfa7efcc5eb3596ca/docs/Data%20Availabilty/on-chain-data.md#L99)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

You can find the code for extracting this data from Ethereum in the repo for Pathfinder, the first StarkNet full node implementation. See [Pathfinder's repo].(https://github.com/eqlabs/pathfinder/blob/2fe6f549a0b8b9923ed7a21cd1a588bc571657d6/crates/pathfinder/src/ethereum/state_update/retrieve.rs).
</blockquote></details>

Done.
___
*[`docs/State/starknet-state.md` line 14 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF1Jt0Ar0K5je7Mk2H:-NB6aV1v-imHCllku6zR:b-s89urv) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L14)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

This should not be "Info" This should be its own section. This is of high importance, and a Note/Info is something that is interesting but can be safely ignored.
</blockquote></details>

I agree, but a nonce section does not belong here, when we have a section for account abstraction we will link to there.

added a TODO
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF0pd00KcxTg6IiFbe:-NAIZzfm7LWrsQd1OWYj:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

contract
</blockquote></details>

Done.
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF14HGDz7OiByifGyW:-NAI_CxL4tci05hGByCQ:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

must
</blockquote></details>

Done.
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF0yiNE_Mk8Y0YVbzz:-NB6_bV9BQBjpRxjvsWf:b-58bh3t) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

that protects against replays
</blockquote></details>

The nonce property itself does not protect against replays.

The addition of protocol rules to have an incremental nonce, and comparing a contract nonce with a nonce field in the transaction does this.
___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF17Z0338tQ132c7hy:-NB6a0LX4xa8hmTmHdQ6:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

in
</blockquote></details>

Done.
___
*[`docs/State/starknet-state.md` line 17 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF1wsZ7LFPR5LpIwHv:-NB6aHIT2gVcu6v1uB8j:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L17)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

General rule: Do NOT use the word "may". It's ambiguous. Use either "might" or "can". In this case, you mean "can".
</blockquote></details>

Done.
___
*[`docs/State/starknet-state.md` line 17 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF2BvN9NLwFRTOQnZE:-NB6aNcd5BYCagFKqSOs:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L17)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

transactions,
</blockquote></details>

Done.

**Review by bbrandtom — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-:-NB7N-y-6anW7Ym8Tq3U:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @ArielElp and @stoobie)

**Review by ArielElp — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-:-NB7_-tf0IySuvkcZRoV:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @stoobie)

**Review by stoobie — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)* status: all files reviewed, 4 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Data Availabilty/on-chain-data.md` line 22 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF2Y3d-pHKPKS_3tfP:-NB7arXW2q1P61Lbq3RU:bvukgom) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/Data%20Availabilty/on-chain-data.md#L22)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Added "value"

It's concatenation, not OR.
</blockquote></details>

Is this Cairo? Or Solidity? I thought that a pipe represents OR and ampersand (&) or plus (+) represents concatenation.

**Review by stoobie — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

___
*[`docs/State/starknet-state.md` line 15 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-NAF0yiNE_Mk8Y0YVbzz:-NB7cXLA2hosyRv8iP-0:b-afc5yh) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/d17e7c4d5ef315bfd4eaa3834d878dad3d2cfef0/docs/State/starknet-state.md#L15)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

The nonce property itself does not protect against replays.

The addition of protocol rules to have an incremental nonce, and comparing a contract nonce with a nonce field in the transaction does this.
</blockquote></details>

Similarly to Ethereum, the contract's nonce is used to provide replay protection at the protocol level. When a transaction is sent to a given contract, the transaction's nonce must match the nonce of the contract. After the transaction is executed, the contract's nonce is increased by one.

**Review by stoobie — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp)

**Review by ArielElp — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/54#-:-NB88LsF6Jro1mX_f4dZ:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @bbrandtom and @stoobie)

**Pull request merged**
