### PR TITLE
changing USER_TOKEN to GITHUB_TOKEN

### PR DESCRIPTION
**Pull request by roi-amaler-starkware**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### PR Preview URL

After you push a commit to this PR, a preview is built and a URL to the root of the preview appears in the comment feed.

Paste here the specific URL(s) of the content that this PR addresses.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/102)

### CODE REVIEW

**Comment by stoobie** [comment]
@roi-amaler-starkware What is the purpose of this change?

**Review by roi-amaler-starkware — COMMENTED** [review]
changed the personal token to a generic github one

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/102#-:-NGI-c8CAjplbP5jqddx:b1x0967)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @stoobie)

**Review by stoobie — APPROVED** [review]
LGTM

**Review by stoobie — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/102#-:-NGWnPtM0KxlqTcaDGpT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roi-amaler-starkware)

**Pull request merged**
