### PR TITLE
docs: Add Network architecture section

### PR DESCRIPTION
**Pull request by stoobie**
### Description of the Changes

TOC: Added new section: Network architecture, includes content currently on docs.starknet.io

### Preview URL

https://starknet-community-libs.github.io/starknet-docs/pr-86/documentation/

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] PR title follows the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @stoobie)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 5 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NF90J-xB6nykc9vzPPX:-NF90J-xB6nykc9vzPPY:bo4u1wp) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/b9356e9385a8c0f4b65b1465d3138de2a259776c/components/StarkNet/modules/develop/nav.adoc#L5)):*
> ```AsciiDoc
> //** xref:ROOT::index.adoc[What Is StarkNet]
> 
> ** StarkNet network architecture
> ```

what about all the other sections? "state","events", etc..

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-86/documentation/ .

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`package.json` line 9 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFbiJTZ0ZNQqEWJnUOL:-NFbiJTZ0ZNQqEWJnUOM:b-g6xu2a) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/34c31e1c4e3cfec1ce037cfee4ca6b91f39bff66/package.json#L9)):*
> ```JSON
>     "release": "standard-version",
>     "release:dry": "standard-version --dry-run",
>     "generate": "antora playbook.yml"
> ```

What is this change? How is this related to the PR?
___
*[`.github/workflows/pull_request.yml` line 18 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFbiNt_AUX21P1mfOdO:-NFbiNta1bEPwglunPh1:b9hs3jd) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/34c31e1c4e3cfec1ce037cfee4ca6b91f39bff66/.github/workflows/pull_request.yml#L18)):*
> ```YAML
>         with:
>           node-version: 16
>       - name: Install node_modules
> ```

What is this change? How is this related to the PR?
Same for all of this file

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-86/documentation/ .

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @ArielElp and @bbrandtom)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 5 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NF90J-xB6nykc9vzPPX:-NFcrcwa3quLMGLPdZjf:brbrmdb) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/b9356e9385a8c0f4b65b1465d3138de2a259776c/components/StarkNet/modules/develop/nav.adoc#L5)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

what about all the other sections? "state","events", etc..
</blockquote></details>

I added these sections in the latest commit. I misinterpreted Henri's comment in the planning doc.
___
*[`package.json` line 9 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFbiJTZ0ZNQqEWJnUOL:-NFctChx9dd9NIAENIW1:b72xzhi) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/34c31e1c4e3cfec1ce037cfee4ca6b91f39bff66/package.json#L9)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

What is this change? How is this related to the PR?
</blockquote></details>

I just had to rebase off of dev. This should no longer appear as a change.
___
*[`.github/workflows/pull_request.yml` line 18 at r6](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFbiNt_AUX21P1mfOdO:-NFcrThkBZHL13pZ1av7:b72xzhi) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/34c31e1c4e3cfec1ce037cfee4ca6b91f39bff66/.github/workflows/pull_request.yml#L18)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

What is this change? How is this related to the PR?
Same for all of this file
</blockquote></details>

I just had to rebase off of dev. This should no longer appear as a change.

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @bbrandtom, @LucasLvy, and @stoobie)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 39 at r7](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFiRHfvCPlIKZUM-lnp:-NFiRHfvCPlIKZUM-lnq:btxi549) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/ec4ce6c9ee6fd88c71b829af42fd847274475890/components/StarkNet/modules/develop/nav.adoc#L39)):*
> ```AsciiDoc
> **** xref:State/starknet-state.adoc[StarkNet state]
> 
> *** xref:CLI/commands.adoc[StarkNet CLI reference]
> ```

Should this be under network architecture? My expectation is that it will be in the same hierarchy, i.e. directly under developing on StarkNet



_Code quote:_
```AsciiDoc
StarkNet CLI reference
```

**Review by bbrandtom — COMMENTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: all files reviewed, 2 unresolved discussions (waiting on @ArielElp and @LucasLvy)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 39 at r7](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFiRHfvCPlIKZUM-lnp:-NFrC28NE4lJ1DiJfD-p:b-cstnkg) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/ec4ce6c9ee6fd88c71b829af42fd847274475890/components/StarkNet/modules/develop/nav.adoc#L39)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

Should this be under network architecture? My expectation is that it will be in the same hierarchy, i.e. directly under developing on StarkNet
</blockquote></details>

I agree

**Review by bbrandtom — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @LucasLvy)

**Review by stoobie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: all files reviewed, 1 unresolved discussion (waiting on @ArielElp and @LucasLvy)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 39 at r7](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFiRHfvCPlIKZUM-lnp:-NFsPm2-8MQwColkBT9_:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/ec4ce6c9ee6fd88c71b829af42fd847274475890/components/StarkNet/modules/develop/nav.adoc#L39)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I agree
</blockquote></details>

Done.

**Comment by dan-ziv** [comment]
Your preview build is ready! ✨ Check the following link in 1-2 minutes: https://starknet-community-libs.github.io/starknet-docs/pr-86/documentation/ .

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @bbrandtom and @LucasLvy)

___
*[`components/StarkNet/modules/develop/nav.adoc` line 39 at r7](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-NFiRHfvCPlIKZUM-lnp:-NFshHLk40ykn3mnlG-W:b-71ck84) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/ec4ce6c9ee6fd88c71b829af42fd847274475890/components/StarkNet/modules/develop/nav.adoc#L39)):*
<details><summary><i>Previously, stoobie (Steve Goodman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Unblocked. Note to move compiler reference under the same hierarchy later

**Review by bbrandtom — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @LucasLvy)

**Review by bbrandtom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-:-NFsi40R9lR2zcNbjfr8:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @LucasLvy)

**Review by ArielElp — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/86#-:-NFsrtdv61y2_ndrPdce:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @bbrandtom and @LucasLvy)

**Pull request merged**
