### PR TITLE
docs: update transaction hash computation

### PR DESCRIPTION
**Pull request by ArielElp**
### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

### Check List

- [ ] Changes have been done against dev branch, and PR does not conflict
- [ ] Docs have been updated
- [ ] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56)

### CODE REVIEW

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Blocks/transactions.md` line 105 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7E-Lb54-VVnHn3T64:-NB7E-Lb54-VVnHn3T65:b-swpy0o) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/251202949ee8410d1cb18e7e473425aaee6a9126/docs/Blocks/transactions.md#L105)):*
> ```Markdown
> </APITable>
> 
> ### Calculating the hash of a v1 invoke transaction
> ```

should it be under the details of v1 invoke transaction?
___
*[`docs/Blocks/transactions.md` line 166 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7EZtH5D05ZB9OpFGA:-NB7EZtH5D05ZB9OpFGB:b-c9ykkf) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/251202949ee8410d1cb18e7e473425aaee6a9126/docs/Blocks/transactions.md#L166)):*
> ```Markdown
> $$
> 
> Where:
> ```

explain what is class hash?
___
*[`docs/Blocks/transactions.md` line 168 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7ERFy2X3p2CkUAHuS:-NB7ERFy2X3p2CkUAHuT:b-hswjw8) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/251202949ee8410d1cb18e7e473425aaee6a9126/docs/Blocks/transactions.md#L168)):*
> ```Markdown
> Where:
> 
> - The placeholders zeros are used to align the hash computation for the different types of transactions (here, they stand for the empty call data and entry point selector)
> ```

This explanation is missing from the invoke v1 transaction

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56)* status: all files reviewed, 2 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`docs/Blocks/transactions.md` line 105 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7E-Lb54-VVnHn3T64:-NB7OGbc-UjyD2uJmOIi:bvh7c1i) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/251202949ee8410d1cb18e7e473425aaee6a9126/docs/Blocks/transactions.md#L105)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

should it be under the details of v1 invoke transaction?
</blockquote></details>

four levels of indentation are not shown in the right, it looks ok imo
___
*[`docs/Blocks/transactions.md` line 168 at r1](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7ERFy2X3p2CkUAHuS:-NB7NdLGCLSPP6M7ANeJ:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/251202949ee8410d1cb18e7e473425aaee6a9126/docs/Blocks/transactions.md#L168)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

This explanation is missing from the invoke v1 transaction
</blockquote></details>

Done.

**Review by bbrandtom — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56)* status: all files reviewed, 3 unresolved discussions (waiting on @ArielElp and @stoobie)

___
*[`docs/Blocks/transactions.md` line 118 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7Ol66-da5jEdv7dBP:-NB7Ol677_-QIDA5p3di:b-248fqo) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/236a9df66e79544e0b7bd86c1977dc99eebfdfd6/docs/Blocks/transactions.md#L118)):*
> ```Markdown
> 
> - $$invoke$$ is a constant prefix string, encoded in ASCII.
> - The placeholder zero is used to align the hash computation for the different types of transactions. Here, it stands for the empty `entry point selector` field that exists in other transaction types.
> ```

I think we shouldn't mention this.
It is just a placeholder, it is of no interest what was here in v0.
___
*[`docs/Blocks/transactions.md` line 170 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7VJhVDro2qtI6p_0y:-NB7VJhW4u-G994prz4Q:b-hmdg4l) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/236a9df66e79544e0b7bd86c1977dc99eebfdfd6/docs/Blocks/transactions.md#L170)):*
> ```Markdown
> 
> - $$declare$$ is a constant prefix string, encoded in ASCII.
> - The placeholders zero is used to align the hash computation for the different types of transactions. Here, it holds the place of `entry_points_selector` that exists in other transaction types.
> ```

same as above, not interesting.
___
*[`docs/Blocks/transactions.md` line 188 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7VR5YByttTH3ArYBr:-NB7VR5YByttTH3ArYBs:bb7od0r) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/236a9df66e79544e0b7bd86c1977dc99eebfdfd6/docs/Blocks/transactions.md#L188)):*
> ```Markdown
> 
> - $$declare$$ is a constant prefix string, encoded in ASCII.
> - The placeholders zeros are used to align the hash computation for the different types of transactions. Here, they stand for the empty `call_data` and `entry_point_selector` that appear in other transaction types.
> ```

same

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @bbrandtom and @stoobie)

___
*[`docs/Blocks/transactions.md` line 118 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7Ol66-da5jEdv7dBP:-NB7bXAF-9-tBCa5H67J:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/236a9df66e79544e0b7bd86c1977dc99eebfdfd6/docs/Blocks/transactions.md#L118)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

I think we shouldn't mention this.
It is just a placeholder, it is of no interest what was here in v0.
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 170 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7VJhVDro2qtI6p_0y:-NB7bXic65B8kL4gUYAE:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/236a9df66e79544e0b7bd86c1977dc99eebfdfd6/docs/Blocks/transactions.md#L170)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

same as above, not interesting.
</blockquote></details>

Done.
___
*[`docs/Blocks/transactions.md` line 188 at r2](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-NB7VR5YByttTH3ArYBr:-NB7bYV84nl32cxC87HI:b-896fix) ([raw file](https://github.com/starknet-community-libs/starknet-docs/blob/236a9df66e79544e0b7bd86c1977dc99eebfdfd6/docs/Blocks/transactions.md#L188)):*
<details><summary><i>Previously, bbrandtom (Tom Brand) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

**Review by bbrandtom — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/56#-:-NB8rwxJDUYGQGnnDx5b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stoobie)

**Pull request merged**
