### PR TITLE
docs: enhance readability of page

### PR DESCRIPTION
**Pull request by emanuel-sol**
### Description of the Changes

The [transaction lifecycle](https://docs.starknet.io/docs/Blocks/transaction-life-cycle) page needed some readability improvements in a couple places 

### Check List

- [x] Changes have been done against dev branch, and PR does not conflict
- [x] Docs have been updated
- [x] PR title is follow the convention: `<docs/feat/fix/chore>(optional scope): <description>`, e.g: `fix: minor typos in code`

---
This change is [Reviewable](https://reviewable.io/reviews/starknet-community-libs/starknet-docs/30)

### CODE REVIEW

**Review by ArielElp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/30)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ArielElp — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/30)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ArielElp and @emanuel-sol)

___
*[`docs/Blocks/transaction-life-cycle.md` line 3 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/30#-N2TEVfT6lAGXyEdDxzY:-N2TEVfT6lAGXyEdDxzZ:b-7fxsdy) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/7caa50a9f201b2eb1bf9e5d4d2d7b8c8e561d5e9/docs/Blocks/transaction-life-cycle.md#L3)):*
> ```Markdown
> # Transaction Lifecycle
> 
> The following are the possible statuses of a transaction from the moment it's included in a proof to the moment it's validated by L1.
> ```

Thanks, that was bad!
___
*[`docs/Blocks/transaction-life-cycle.md` line 38 at r1](https://reviewable.io/reviews/starkware-libs/starknet-docs/30#-N2TEZa04Xurs_csbk1e:-N2TEZa04Xurs_csbk1f:beciru3) ([raw file](https://github.com/starkware-libs/starknet-docs/blob/7caa50a9f201b2eb1bf9e5d4d2d7b8c8e561d5e9/docs/Blocks/transaction-life-cycle.md#L38)):*
> ```Markdown
> ## The pending block
> 
> Today, StarkNet supports querying the new block before its construction is complete. This feature improves the uptime of the system prior to the decentralization phase, but will probably become obsolete once the system is decentralized, as full nodes will only propagate finalized blocks through the network.
> ```

I don't like uptime here, maybe responsiveness, because the system is still up and creating the block even if the apis don't report it.

**Comment by emanuel-sol** [comment]
> I don't like uptime here, maybe responsiveness, because the system is still up and creating the block even if the apis don't report it.

@ArielElp I agree, responsiveness makes more sense.

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/30#-:-N2eBkiJCPCNQudS1UtZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @emanuel-sol)

**Review by ArielElp — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/starknet-docs/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @emanuel-sol)

**Pull request merged**
